//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImageDFS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageServerInfo
    {
        public ImageServerInfo()
        {
            this.ImageInfo = new HashSet<ImageInfo>();
        }
    
        public int ServerId { get; set; }
        public string ServerName { get; set; }
        public string ServerUrl { get; set; }
        public string PicRootPath { get; set; }
        public int MaxPicAmount { get; set; }
        public int CurPicAmount { get; set; }
        public bool FlgUsable { get; set; }
    
        public virtual ICollection<ImageInfo> ImageInfo { get; set; }
    }
}
